Prepare the data

In [1]:
alphabets = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [2]:
len(alphabets)

26

Preprocess the data

In [3]:
int_to_char = dict(enumerate(alphabets))
int_to_char

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L',
 12: 'M',
 13: 'N',
 14: 'O',
 15: 'P',
 16: 'Q',
 17: 'R',
 18: 'S',
 19: 'T',
 20: 'U',
 21: 'V',
 22: 'W',
 23: 'X',
 24: 'Y',
 25: 'Z'}

In [4]:
char_to_int = dict((v,i) for i, v in enumerate(alphabets))
char_to_int

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'J': 9,
 'K': 10,
 'L': 11,
 'M': 12,
 'N': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [5]:
int_to_char[5]

'F'

In [6]:
char_to_int['H']

7

In [7]:
seq_length = 1

In [8]:
x = []
y = []
for i in range(len(alphabets)-seq_length):
    seq_in = [alphabets[i]]
    seq_out = alphabets[i+1]
    x += [[char_to_int[seq_in[0]]]]
    y += [char_to_int[seq_out]]
    print(seq_in, '->', seq_out)

['A'] -> B
['B'] -> C
['C'] -> D
['D'] -> E
['E'] -> F
['F'] -> G
['G'] -> H
['H'] -> I
['I'] -> J
['J'] -> K
['K'] -> L
['L'] -> M
['M'] -> N
['N'] -> O
['O'] -> P
['P'] -> Q
['Q'] -> R
['R'] -> S
['S'] -> T
['T'] -> U
['U'] -> V
['V'] -> W
['W'] -> X
['X'] -> Y
['Y'] -> Z


In [9]:
x

[[0],
 [1],
 [2],
 [3],
 [4],
 [5],
 [6],
 [7],
 [8],
 [9],
 [10],
 [11],
 [12],
 [13],
 [14],
 [15],
 [16],
 [17],
 [18],
 [19],
 [20],
 [21],
 [22],
 [23],
 [24]]

In [10]:
y

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25]

#### One hot encoding

In [11]:
from tensorflow.keras.utils import to_categorical

2023-12-18 12:12:18.409070: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-18 12:12:18.412900: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-18 12:12:18.470760: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-18 12:12:18.470802: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-18 12:12:18.472191: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to

In [12]:
y_new = to_categorical(y)

In [13]:
y_new

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 

In [14]:
y_new.shape

(25, 26)

In [15]:
import numpy as np

In [16]:
np.array(x).shape

(25, 1)

In [17]:
x = np.reshape(x, (25,1,1))
x.shape

(25, 1, 1)

In [18]:
x

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]]])

In [19]:
x = x / 25
x

array([[[0.  ]],

       [[0.04]],

       [[0.08]],

       [[0.12]],

       [[0.16]],

       [[0.2 ]],

       [[0.24]],

       [[0.28]],

       [[0.32]],

       [[0.36]],

       [[0.4 ]],

       [[0.44]],

       [[0.48]],

       [[0.52]],

       [[0.56]],

       [[0.6 ]],

       [[0.64]],

       [[0.68]],

       [[0.72]],

       [[0.76]],

       [[0.8 ]],

       [[0.84]],

       [[0.88]],

       [[0.92]],

       [[0.96]]])

#### Build the model

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [21]:
model = Sequential()

model.add(Dense(25, input_shape=(1,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation = 'softmax'))

In [22]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [39]:
model.fit(x,y_new, epochs=100, batch_size=1)

Epoch 1/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4719 - accuracy: 0.9600
Epoch 2/100
25/25 [==============================] - 0s 5ms/step - loss: 0.4705 - accuracy: 0.8800
Epoch 3/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4749 - accuracy: 0.8400
Epoch 4/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4577 - accuracy: 0.8800
Epoch 5/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4614 - accuracy: 0.9200
Epoch 6/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4628 - accuracy: 0.8800
Epoch 7/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4766 - accuracy: 0.9200
Epoch 8/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4608 - accuracy: 0.9600
Epoch 9/100
25/25 [==============================] - 0s 6ms/step - loss: 0.4705 - accuracy: 0.9200
Epoch 10/100
25/25 [==============================] - 0s 5ms/step - loss: 0.4578 - accuracy: 0.9600
Epoch 11/

In [40]:
model.evaluate(x, y_new, batch_size=1)

25/25 [==============================] - 0s 4ms/step - loss: 0.3568 - accuracy: 1.0000


[0.3568493723869324, 1.0]

#### Predict on the new data

In [41]:
new = 'A'
a = char_to_int[new]
a = np.array(a)
a = np.reshape(a, (1,1,1))
a.shape

x_test = a / 25
x_test

pred = model.predict(x_test)
pred = pred.argmax(axis=1)
int_to_char[pred[0]]

1/1 [==============================] - 0s 45ms/step


'B'

In [42]:
def predict(char):
    a = char_to_int[char]
    a = np.array(a)
    a = np.reshape(a, (1,1,1))
    x_test = a / 25
    pred = model.predict(x_test,verbose=0)
    pred = pred.argmax(axis=1)
    return int_to_char[pred[0]]


In [43]:
predict('A')

'B'

In [44]:
predict('E')

'F'

In [45]:
predict('B')

'C'

In [49]:
alphabet = 'A'
for i in range(26):
    print(alphabet,end=' ') 
    alphabet = predict(alphabet)
    
    

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z 

In [29]:
seq_length = 3

In [30]:
x = []
y = []
for i in range(len(alphabets)-seq_length):
    seq_in = alphabets[i:i+seq_length]
    seq_out = alphabets[i+seq_length]
    x.append([char_to_int[char] for char in seq_in])
    y.append([char_to_int[seq_out]])
    print(seq_in, '->', seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [31]:
x

[[0, 1, 2],
 [1, 2, 3],
 [2, 3, 4],
 [3, 4, 5],
 [4, 5, 6],
 [5, 6, 7],
 [6, 7, 8],
 [7, 8, 9],
 [8, 9, 10],
 [9, 10, 11],
 [10, 11, 12],
 [11, 12, 13],
 [12, 13, 14],
 [13, 14, 15],
 [14, 15, 16],
 [15, 16, 17],
 [16, 17, 18],
 [17, 18, 19],
 [18, 19, 20],
 [19, 20, 21],
 [20, 21, 22],
 [21, 22, 23],
 [22, 23, 24]]

In [32]:
y_new = to_categorical(y)

In [33]:
len(x)

23

In [34]:
np.array(x).shape

(23, 3)

In [35]:
x = np.reshape(x, (23,seq_length,1))
x.shape

(23, 3, 1)

In [36]:
x = x / 25
x

array([[[0.  ],
        [0.04],
        [0.08]],

       [[0.04],
        [0.08],
        [0.12]],

       [[0.08],
        [0.12],
        [0.16]],

       [[0.12],
        [0.16],
        [0.2 ]],

       [[0.16],
        [0.2 ],
        [0.24]],

       [[0.2 ],
        [0.24],
        [0.28]],

       [[0.24],
        [0.28],
        [0.32]],

       [[0.28],
        [0.32],
        [0.36]],

       [[0.32],
        [0.36],
        [0.4 ]],

       [[0.36],
        [0.4 ],
        [0.44]],

       [[0.4 ],
        [0.44],
        [0.48]],

       [[0.44],
        [0.48],
        [0.52]],

       [[0.48],
        [0.52],
        [0.56]],

       [[0.52],
        [0.56],
        [0.6 ]],

       [[0.56],
        [0.6 ],
        [0.64]],

       [[0.6 ],
        [0.64],
        [0.68]],

       [[0.64],
        [0.68],
        [0.72]],

       [[0.68],
        [0.72],
        [0.76]],

       [[0.72],
        [0.76],
        [0.8 ]],

       [[0.76],
        [0.8 ],
        [0.84]],



In [37]:
len(x)

23

In [38]:
model = Sequential()

model.add(Dense(25, input_shape=(3,1), activation='relu'))
model.add(LSTM(128))
model.add(Dense(26, activation = 'softmax'))

In [39]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
model.fit(x,y_new, epochs=1000, batch_size=1)

Epoch 1/1000
23/23 [==============================] - 3s 7ms/step - loss: 3.2810 - accuracy: 0.0435
Epoch 2/1000
23/23 [==============================] - 0s 7ms/step - loss: 3.2468 - accuracy: 0.0435
Epoch 3/1000
23/23 [==============================] - 0s 8ms/step - loss: 3.2288 - accuracy: 0.0435
Epoch 4/1000
23/23 [==============================] - 0s 7ms/step - loss: 3.2033 - accuracy: 0.0435
Epoch 5/1000
23/23 [==============================] - 0s 8ms/step - loss: 3.1661 - accuracy: 0.0435
Epoch 6/1000
23/23 [==============================] - 0s 6ms/step - loss: 3.1211 - accuracy: 0.0000e+00
Epoch 7/1000
23/23 [==============================] - 0s 7ms/step - loss: 3.0717 - accuracy: 0.0000e+00
Epoch 8/1000
23/23 [==============================] - 0s 7ms/step - loss: 3.0225 - accuracy: 0.0000e+00
Epoch 9/1000
23/23 [==============================] - 0s 7ms/step - loss: 2.9676 - accuracy: 0.0435
Epoch 10/1000
23/23 [==============================] - 0s 7ms/step - loss: 2.9092 - accu

In [41]:
model.evaluate(x, y_new, batch_size=1)

23/23 [==============================] - 1s 4ms/step - loss: 0.0154 - accuracy: 1.0000


[0.015406022779643536, 1.0]

In [42]:
def predict(seq):
    a = []
    a.append([char_to_int[char] for char in seq])
    a = np.array(a)
    a = np.reshape(a, (1,3,1))
    x_test = a / 25
    pred = model.predict(x_test)
    pred = pred.argmax(axis=1)
    return int_to_char[pred[0]]


In [43]:
predict('ABC')

1/1 [==============================] - 1s 582ms/step


'D'

In [44]:
predict('WXY')

1/1 [==============================] - 0s 29ms/step


'Z'

In [45]:
predict('LMN')

1/1 [==============================] - 0s 27ms/step


'O'